# Generated by Django 5.1.6 on 2025-02-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_admin_app', '0002_ofertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='em_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
