# Generated by Django 5.1.6 on 2025-02-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_admin_app', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=15)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão')], max_length=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_admin_app.produto')),
            ],
        ),
    ]
