# Generated by Django 5.1.6 on 2025-02-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_admin_app', '0006_ofertas_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='produto',
        ),
    ]
