# Generated by Django 5.1.6 on 2025-02-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_admin_app', '0007_remove_ofertas_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja_admin_app.produto'),
        ),
    ]
