# Generated by Django 5.1.6 on 2025-02-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_admin_app', '0009_pedido_preco_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ofertas',
        ),
    ]
